# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='addtrss',
            new_name='address',
        ),
    ]
